# Generated by Django 3.2.16 on 2023-12-24 15:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='user',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date_time_end_sending',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 15, 12, 50, 74117, tzinfo=utc), verbose_name='Конец рассылки'),
        ),
    ]
