# Generated by Django 3.2.16 on 2023-12-24 15:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20231224_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='date_time_end_sending',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 15, 53, 0, 660768, tzinfo=utc), verbose_name='Конец рассылки'),
        ),
    ]
