# Generated by Django 3.2.16 on 2023-12-24 16:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_mailing_date_time_end_sending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='date_time_end_sending',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 16, 25, 27, 581508, tzinfo=utc), verbose_name='Конец рассылки'),
        ),
    ]
